{
  "hash": "7667291dd87b82c0416ef991b7e442a8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Dalanda Jalloh\"\ndate: 4/9/26\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\nIn this lab, you will apply the spatial predictive modeling techniques demonstrated \nin the class exercise using a different 311 service request type of your choice as the predictor variable. You will build a complete spatial predictive model, document your process, and interpret your results.\n\n### Learning Objectives\n\nBy completing this assignment, you will demonstrate your ability to:\n\n- Adapt example code to analyze a new dataset\n- Build spatial features for predictive modeling\n- Apply count regression techniques to spatial data\n- Implement spatial cross-validation\n- Interpret and communicate model results\n- Critically evaluate model performance\n\n---\n\n## Step 1: Choose Your 311 Violation Type\n\n### Getting the Data\n\nVisit the Chicago 311 Service Requests dataset:\n\n<https://data.cityofchicago.org/stories/s/311-Dataset-Changes-12-11-2018/d7nq-5g7t>\n\nBrowse the available service request types (e.g., Graffiti Removal, Pothole Repair, Street Light Out, Sanitation Code Violations, etc.) and **choose one violation type** that interests you.\n\n### Requirements for Your Choice\n\n- Choose a **different** violation type than the abandoned cars we did in class.\n---\n\n## Step 2: Complete the Analysis\n\nUsing the class exercise as your template, adapt the code to analyze your chosen 311 violation type.\n\n### What to Include\n\nWork through all major sections of the analysis:\n\n#### Part 0: Setup\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(lubridate)\nlibrary(fixest)\n\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_crime <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_crime())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: C:/Users/dalan/Desktop/PPA_CPLN5920/GitHub/CPLN5920_Jalloh_Portfolio_2/labs/lab_4 \n```\n\n\n:::\n:::\n\n#### Part 1: Data Loading & Exploration\n- Load your 311 data and Chicago spatial boundaries\n- Create visualizations showing the spatial distribution of your violation type\n- Describe patterns you observe\n\n::: {.cell}\n\n```{.r .cell-code}\n#1.1 Load Chicago Spatial Data \n\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n#Chicago boundary \nchicago_boundary<- st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\nAnalysis: In step 1.1, I loaded the needed spatial data for the analysis which was easily accessible from the city of Chicago's open data portal. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#1.2 Load Rodent Complaint Data \n\nrodent_data<- read.csv(\"data/raw/311_Service_Requests_-_Rodent_Baiting_-_Historical_20260411.csv\")\n\nrodent_data$Creation.Date <- mdy(rodent_data$Creation.Date)\n\nrodent_data_filter <- rodent_data %>% \n  filter(between(Creation.Date,\n                 as.Date(\"2018-01-01\"),\n                 as.Date(\"2018-12-31\"))) %>% \n  filter(Status== \"Completed\")\n\nrodent_data_filter<- rodent_data_filter %>% \n  filter(!is.na(Longitude), !is.na(Latitude))\n\nrodent_data_filter <- st_as_sf(rodent_data_filter, coords = c(\"Longitude\", \"Latitude\"), crs = 4326)\nrodent_data_filter <- st_transform(rodent_data_filter, 'ESRI:102271')\n\nglimpse(rodent_data_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 37,379\nColumns: 19\n$ Creation.Date                   <date> 2018-12-16, 2018-12-16, 2018-12-16, 2…\n$ Status                          <chr> \"Completed\", \"Completed\", \"Completed\",…\n$ Completion.Date                 <chr> \"12/17/2018\", \"12/17/2018\", \"12/17/201…\n$ Service.Request.Number          <chr> \"18-03374877\", \"18-03374710\", \"18-0337…\n$ Type.of.Service.Request         <chr> \"Rodent Baiting/Rat Complaint\", \"Roden…\n$ Number.of.Premises.Baited       <chr> \"5\", \"1\", \"3\", \"3\", \"2\", \"4\", \"1\", \"3\"…\n$ Number.of.Premises.with.Garbage <chr> \"6\", \"3\", \"8\", \"4\", \"2\", \"5\", \"2\", \"10…\n$ Number.of.Premises.with.Rats    <chr> \"0\", \"3\", \"3\", \"3\", \"3\", \"8\", \"1\", \"2\"…\n$ Current.Activity                <chr> \"Dispatch Crew\", \"Dispatch Crew\", \"Dis…\n$ Most.Recent.Action              <chr> \"Inspected and baited\", \"No contact, l…\n$ Street.Address                  <chr> \"3525 W LE MOYNE ST\", \"2236 W 35TH ST\"…\n$ ZIP.Code                        <int> 60651, 60609, 60626, 60639, 60639, 606…\n$ X.Coordinate                    <dbl> 1152585, 1161910, 1163203, 1143359, 11…\n$ Y.Coordinate                    <dbl> 1909743, 1881433, 1946993, 1914554, 19…\n$ Ward                            <int> 26, 12, 49, 36, 31, 12, 13, 1, 11, 12,…\n$ Police.District                 <int> 14, 9, 24, 25, 25, 10, 8, 14, 9, 9, 8,…\n$ Community.Area                  <int> 23, 59, 1, 19, 19, 30, 64, 22, 61, 59,…\n$ Location                        <chr> \"(41.908194331345, -87.714916523819)\",…\n$ geometry                        <POINT [m]> POINT (351309.2 582089.9), POINT…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the data\ncat(\"\\n✓ Loaded rodent data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded rodent data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of rodent complaints:\", nrow(rodent_data_filter), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of rodent complaints: 37379 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(rodent_data)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: NA \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", format(min(rodent_data_filter$Creation.Date, na.rm = TRUE)), \"to\", \n    format(max(rodent_data_filter$Creation.Date, na.rm = TRUE)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 2018-01-01 to 2018-12-16 \n```\n\n\n:::\n:::\n\nAnalysis: In step 1.2, I filtered my data to only include complaints made in the most updated year of the data-set, 2018. I choose to analyze rodent complaints because cities are heavily burdened by the destruction that rats cause. They pose public health and ecological risks and damage infrastructure. If cities are able to predict where rats are likely to be appear they can plan for and minimize their damage. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#1.3 Visualize Point Data \n#| fig-width: 10\n#| fig-height: 5\n\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicago_boundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = rodent_data_filter, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Rodent Complaints\",\n    subtitle = paste0(\"Chicago 2018, n = \", nrow(rodent_data_filter))\n  )\n\np2 <- ggplot() + \n  geom_sf(data = chicago_boundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(rodent_data_filter)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Rodent Complaints in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nAnalysis: In step 1.3, I was able to map the spatial locations of the complaints and create a kernel density map which smoothed the points out to better see where they were concentrated within the context of the Chicago. \n\n#### Part 2: Fishnet Grid Creation\n- Create a 500m x 500m fishnet grid\n- Aggregate your violations to grid cells\n- Visualize the count distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#2.1 Understanding the Fishnet \n\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicago_boundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number()) %>%\n  st_transform('ESRI:102271') \n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicago_boundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n\n```{.r .cell-code}\n#2.2 Aggregate Burglaries to Grid \n\n# Spatial join: which cell contains each rodent complaint?\nrodent_fishnet <- st_join(rodent_data_filter, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countrodent_data_filter = n()) \n\nglimpse(rodent_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,916\nColumns: 2\n$ uniqueID                <int> 38, 50, 91, 92, 102, 104, 144, 145, 155, 156, …\n$ countrodent_data_filter <int> 1, 1, 2, 1, 1, 3, 1, 8, 1, 4, 2, 18, 7, 3, 1, …\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(rodent_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet <- fishnet %>%\n  left_join(rodent_fishnet, by = \"uniqueID\") %>%\n  mutate(countrodent_data_filter = replace_na(countrodent_data_filter, 0))\n\n# Summary statistics\ncat(\"\\nrodents count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nrodents count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countrodent_datasf_proj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLength  Class   Mode \n     0   NULL   NULL \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero rodents:\", \n    sum(fishnet$rodent_data_filter == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countrodent_data_filter == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero rodents: 0 / 2458 ( 22.1 %)\n```\n\n\n:::\n:::\n\nAnalysis: In part 2, a fishnet grid was created for the city of Chicago. A fishnet grid places the point data (complaints) over a grid of cells that acts as the spatial unit needed to aggregate counts and do other spatial analyses. Because 15.8% of the grids had 0 complaints, it is likely that overdispersion (mean =/ variance) become an issue when running the regression later on.  \n\n#### Part 3: Spatial Features\n- Calculate k-nearest neighbor features\n- Perform Local Moran's I analysis\n- Identify hot spots and cold spots\n- Create distance-to-hotspot measures\n- Join any additional contextual data if you are looking for more to do and really get into this (e.g., demographics, land use)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#3.1 Create a Kernel Density Baseline \n\n# Convert burglaries to ppp (point pattern) format for spatstat\nrodents_ppp <- as.ppp(\n  st_coordinates(rodent_data_filter),\n  W = as.owin(st_bbox(chicago_boundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_rodents <- density.ppp(\n  rodents_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_rodents)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicago_boundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple Spatial Smoothing of Rodent Complaint locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nAnalysis: In step 3.1, a baseline density map is created as a benchmark to compare our model to. It works by converting the point into a raster overlay to better see where the points are concentrated within the city. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#3.2 Create Spatial Predictor Variable \n\ngarbage_carts<- read.csv(\"data/raw/311_Service_Requests_-_Garbage_Carts_-_Historical_20260411.csv\") %>% \n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n\ngarbage_carts$Creation.Date <- mdy(garbage_carts$Creation.Date)\n\ngarbage_carts<- garbage_carts %>% \n  filter(between(Creation.Date,\n                 as.Date(\"2018-01-01\"),\n                 as.Date(\"2018-12-31\"))) %>% \n  filter(Status== \"Completed\")\n\n# Aggregate garbage cart to fishnet\ncarts_fishnet <- st_join(garbage_carts, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(carts = n())\n\n# Join to fishnet\nfishnet <- fishnet %>%\n  left_join(carts_fishnet, by = \"uniqueID\") %>%\n  mutate(carts = replace_na(carts, 0))\n\ncat(\" Cart distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Cart distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$carts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    2.00   12.00   14.27   23.00   66.00 \n```\n\n\n:::\n\n```{.r .cell-code}\n#visualize the data \n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = carts), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Garbage Carts\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countrodent_data_filter), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Rodent Complaints\") +\n  theme_crime()\n\np1 + p2 +\n  plot_annotation(title = \"Are garbage carts and rodent complaints correlated?\")\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nAnalysis: In step 3.2, I am using garbage cart locations as a spatial predictor that can hopefully be used to predict the occurrence of rodent complaints. After the data is downloaded, it's joined to the fishnet data frame created in the previous step so that the points can be aggregated. Upon initial glance of the two maps side by side, there does not seem to be any correlation between where garbage carts are located and where complaints are being called from. There is some overlap in certain areas but overall not as much as I suspected when I originally choose garbage cart lcoations as a predictor. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#3.3 Nearest Neighbor Feature\n\n# Calculate mean distance to 3 nearest garbage carts \n# (Do this OUTSIDE of mutate to avoid sf conflicts)\n\n# Get coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\ncarts_coords <- st_coordinates(garbage_carts)\n\n# Calculate k nearest neighbors and distances\nnn_result <- get.knnx(carts_coords, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    carts.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$carts.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   5.149   72.860  120.587  258.191  276.213 2321.007 \n```\n\n\n:::\n:::\n\nAnalysis: In step 3.3, K nearest neighbors is used here to measure the average distance to 3 garbage cart locations. This helps to capture a spillover effect- how likely are rodent complaints affected by nearby garbage trucks. Once the mean distance was calculated, this value was joined with the fishnet data set to represent the mean distance per grid cell. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#3.4 Distance to Hotspot \n\ncalculate_local_morans_knn_safe <- function(data, variable, k = 5) {\n  keep <- !is.na(data[[variable]]) & !st_is_empty(data)\n  data_sub <- data[keep, ]\n  \n  pts <- st_point_on_surface(st_geometry(data_sub))\n  coords <- st_coordinates(pts)\n  \n  knn <- knearneigh(coords, k = k)\n  nb <- knn2nb(knn)\n  lw <- nb2listw(nb, style = \"W\", zero.policy = TRUE)\n  \n  lm <- localmoran(data_sub[[variable]], lw, zero.policy = TRUE)\n  mean_val <- mean(data_sub[[variable]], na.rm = TRUE)\n  \n  data$local_i <- NA_real_\n  data$p_value <- NA_real_\n  data$is_significant <- NA\n  data$moran_class <- NA_character_\n  \n  data$local_i[keep] <- lm[, 1]\n  data$p_value[keep] <- lm[, 5]\n  data$is_significant[keep] <- data$p_value[keep] < 0.05\n  \n  vals <- data[[variable]]\n  sig <- data$is_significant\n  li <- data$local_i\n  \n  data$moran_class <- dplyr::case_when(\n    !sig ~ \"Not Significant\",\n    li > 0 & vals > mean_val ~ \"High-High\",\n    li > 0 & vals <= mean_val ~ \"Low-Low\",\n    li < 0 & vals > mean_val ~ \"High-Low\",\n    li < 0 & vals <= mean_val ~ \"Low-High\",\n    TRUE ~ \"Not Significant\"\n  )\n  \n  data\n}\n\n# Apply to garbage carts \nfishnet <- calculate_local_morans_knn_safe(fishnet, \"carts\", k = 5)\n\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Garbage Carts Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_point_on_surface()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_point_on_surface(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to abandoned car hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to abandoned car hot spots\n  - Number of hot spot cells: 317 \n```\n\n\n:::\n:::\n\nAnalysis: In step 3.4, local Moran's I identifies clusters or hotpots of where garbage carts are located and whether the clustering is significant or not. Afterwards, the hotspots are defined such as high-high and low-low which represents where high values cluster together and where low values cluster together. Then each grid's distance(from the centroid) to the nearest cluster is calculated. High-high clustering appears in the center of the city while low-low clustering appears more so on the eastern edges of the city. \n\n#### Part 4: Count Regression Models\n- Fit Poisson regression\n- Fit Negative Binomial regression\n- Compare model fit (AIC)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#4.1 Join Police Districts for Cross Validation \n\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) \n\nfishnet<- fishnet %>% \nfilter(!is.na(District))  # Remove cells outside districts\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 1708 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#4.2 Poisson Regression \n\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::transmute(\n    uniqueID = uniqueID,\n    District = District,\n    countrodent_data_filter = as.numeric(countrodent_data_filter),\n    carts = as.numeric(carts),\n    carts.nn = as.numeric(carts.nn),\n    dist_to_hotspot = as.numeric(dist_to_hotspot)\n  ) %>%\n  dplyr::filter(\n    is.finite(countrodent_data_filter),\n    is.finite(carts),\n    is.finite(carts.nn),\n    is.finite(dist_to_hotspot)\n  )\n\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 1708 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\", ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 6 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fit Poisson regression\n\nmodel_poisson <- fepois(\n  countrodent_data_filter ~ carts + carts.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson estimation, Dep. Var.: countrodent_data_filter\nObservations: 1,708\nStandard-errors: IID \n                 Estimate Std. Error  z value  Pr(>|z|)    \n(Intercept)      2.961886 0.02282403 129.7705 < 2.2e-16 ***\ncarts            0.018350 0.00057224  32.0673 < 2.2e-16 ***\ncarts.nn        -0.004227 0.00009440 -44.7789 < 2.2e-16 ***\ndist_to_hotspot  0.000045 0.00000379  12.0127 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nLog-Likelihood: -14,876.8   Adj. Pseudo R2: 0.27371 \n           BIC:  29,783.4     Squared Cor.: 0.222272\n```\n\n\n:::\n:::\n\nAnalysis: The results of the poisson regression show that all the predictors used in the model are significant as indicated by the p value of less than .05. Both carts and distance to hotspot have a rate ratio slighty above 1. This indicates that when garbage carts increase by one unit, so do rodent complaints. As distance to nearby garbage carts increase by one unit, rodent complaints decrease. As distance from hotspots increase, rodent complaints only slightly increase and should be interpreted with caution. \n\n::: {.cell}\n\n```{.r .cell-code}\n#4.3 Checking for over-dispersion \n\n# Calculate dispersion parameter\n\n# Pearson residuals\npearson_resid <- residuals(model_poisson, type = \"pearson\")\n\n# Number of observations\nn <- nobs(model_poisson)\n\n# Number of parameters\nk <- length(coef(model_poisson))\n\n# Dispersion statistic\ndispersion <- sum(pearson_resid^2, na.rm = TRUE) / (n - k)\n\ndispersion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.57746\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 16.58 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\nAnalysis: Over-dispersion is likely happening because many grid cells have zero or low rodent complaints, while a few have very high counts. This creates a lot of variation in the data, making the variance larger than the mean, which means that the Poisson model is not appropriate.\n\n::: {.cell}\n\n```{.r .cell-code}\n#4.4 Negative binomial regression \n\n# Fit Negative Binomial model\n\nmodel_nb <- fenegbin(\n  countrodent_data_filter ~ carts + carts.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nML estimation, family = Negative Binomial\nDep. Var.: countrodent_data_filter\nObservations: 1,708\nStandard-errors: IID \n                 Estimate Std. Error   z value    Pr(>|z|)    \n(Intercept)      2.791544   0.088369  31.58979   < 2.2e-16 ***\ncarts            0.024224   0.002790   8.68273   < 2.2e-16 ***\ncarts.nn        -0.004302   0.000217 -19.86761   < 2.2e-16 ***\ndist_to_hotspot  0.000079   0.000018   4.33816 0.000014368 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nOver-dispersion parameter: theta = 1.026066  \nLog-Likelihood: -6,151.2   Adj. Pseudo R2: 0.064134\n           BIC: 12,332.1     Squared Cor.: 0.216214\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare AIC (lower is better)\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 29761.6 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 12310.4 \n```\n\n\n:::\n:::\n\nAnalysis: In step 4.4 we try to fit our data with a negative binomial model which is better at handling data with dispersion. The AIC shows the negative binomial model is a better fit as indicated by the smaller value of 12310 in comparison to Poisson's value of 29761.6. \n\n#### Part 5: Spatial Cross-Validation (2017)\n- Implement Leave-One-Group-Out cross-validation on 2017 data\n- Calculate and report error metrics (MAE, RMSE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#5.1 Leave One Group Out Cross-Validation\n#5.2 Run Metrics \n\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n   model_cv <- fenegbin(\n    countrodent_data_filter ~ carts + carts.nn + dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, newdata = test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countrodent_data_filter - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countrodent_data_filter - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district, \n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 22 - District 5 - MAE: 9.09 \n  Fold 2 / 22 - District 4 - MAE: 10.82 \n  Fold 3 / 22 - District 22 - MAE: 15.19 \n  Fold 4 / 22 - District 6 - MAE: 10.74 \n  Fold 5 / 22 - District 8 - MAE: 12.09 \n  Fold 6 / 22 - District 7 - MAE: 8.34 \n  Fold 7 / 22 - District 3 - MAE: 8.71 \n  Fold 8 / 22 - District 2 - MAE: 9.09 \n  Fold 9 / 22 - District 9 - MAE: 10.27 \n  Fold 10 / 22 - District 10 - MAE: 15.3 \n  Fold 11 / 22 - District 1 - MAE: 8.43 \n  Fold 12 / 22 - District 12 - MAE: 14 \n  Fold 13 / 22 - District 15 - MAE: 11.33 \n  Fold 14 / 22 - District 11 - MAE: 11.55 \n  Fold 15 / 22 - District 18 - MAE: 14.86 \n  Fold 16 / 22 - District 25 - MAE: 12.22 \n  Fold 17 / 22 - District 14 - MAE: 26.06 \n  Fold 18 / 22 - District 19 - MAE: 27.47 \n  Fold 19 / 22 - District 16 - MAE: 15.6 \n  Fold 20 / 22 - District 17 - MAE: 13.88 \n  Fold 21 / 22 - District 20 - MAE: 15.56 \n  Fold 22 / 22 - District 24 - MAE: 17.54 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Overall results\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 13.55 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 18.55 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Show results\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 27.47 </td>\n   <td style=\"text-align:right;\"> 35.16 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 26.06 </td>\n   <td style=\"text-align:right;\"> 34.12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 17.54 </td>\n   <td style=\"text-align:right;\"> 23.35 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 15.60 </td>\n   <td style=\"text-align:right;\"> 18.96 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 15.56 </td>\n   <td style=\"text-align:right;\"> 24.32 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 15.30 </td>\n   <td style=\"text-align:right;\"> 23.37 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 15.19 </td>\n   <td style=\"text-align:right;\"> 17.41 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 14.86 </td>\n   <td style=\"text-align:right;\"> 19.56 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 14.00 </td>\n   <td style=\"text-align:right;\"> 22.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 13.88 </td>\n   <td style=\"text-align:right;\"> 21.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 12.22 </td>\n   <td style=\"text-align:right;\"> 18.26 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 12.09 </td>\n   <td style=\"text-align:right;\"> 16.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 11.55 </td>\n   <td style=\"text-align:right;\"> 14.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 11.33 </td>\n   <td style=\"text-align:right;\"> 14.08 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 10.82 </td>\n   <td style=\"text-align:right;\"> 16.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 10.74 </td>\n   <td style=\"text-align:right;\"> 14.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 10.27 </td>\n   <td style=\"text-align:right;\"> 15.92 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 9.09 </td>\n   <td style=\"text-align:right;\"> 11.80 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 9.09 </td>\n   <td style=\"text-align:right;\"> 11.01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 8.71 </td>\n   <td style=\"text-align:right;\"> 11.56 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 8.43 </td>\n   <td style=\"text-align:right;\"> 11.97 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 8.34 </td>\n   <td style=\"text-align:right;\"> 11.02 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\nAnalysis: After running the cross validation we see that on average, the model’s predictions differ from observed rodent complaint counts by about 14 complaints per grid cell. The RMSE of 18.55 (which is higher than the MAE of 13.55) indicates that the model has a harder time predicting larger errors. The errors do vary across the different districts as well with the lowest MAE being 8.34 and the highest being 27.47. This indicates that some districts are harder to predict than others. \n\n#### Part 6: Model Evaluation\n- Compare to KDE baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#6.1 Generate Final Predictions\n#6.2 Compare Model vs KDE Baseline \n\n# Fit final model on all data\nfinal_model <- fenegbin(\n  countrodent_data_filter ~ carts + carts.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, newdata = fishnet_model, type = \"response\")[\n      match(uniqueID, fishnet_model$uniqueID)\n    ]\n  )\n\n# Also add KDE predictions (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countrodent_data_filter, na.rm = TRUE)\n\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n\n#compare models \n\n# Create three maps\n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countrodent_data_filter), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits= c(0,15)) + \n  labs(title = \"Actual Rodent Complaints\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits= c(0,15)) + \n  labs(title = \"Model Predictions (Neg. Bin)\") +\n  theme_crime()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits= c(0, 15)) + \n  labs(title = \"KDE Baseline Predictions\") +\n  theme_crime()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countrodent_data_filter - prediction_nb)),\n    model_rmse = sqrt(mean((countrodent_data_filter - prediction_nb)^2)),\n    kde_mae = mean(abs(countrodent_data_filter - prediction_kde)),\n    kde_rmse = sqrt(mean((countrodent_data_filter - prediction_kde)^2))\n  )\n\ncomparison %>%\n  tidyr::pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  tidyr::separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  tidyr::pivot_wider(names_from = metric, values_from = value) %>%\n  knitr::kable(\n    digits = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kableExtra::kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 12.36 </td>\n   <td style=\"text-align:right;\"> 17.94 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 9.61 </td>\n   <td style=\"text-align:right;\"> 14.51 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\nAnalysis: After using the model on all of the data at once, we can compare it with our baseline KDE model and where rodent complaints actually occurred. There is a big discrepancy between where the complaints appear in the city of Chicago. The spatial model(negative binomial) in general seems to underpredict more than it over predicts, although some areas are more over predicted. This can be due to poor predicting power of the model which could have been strengthened with more predictors. The KDE baseline model underpredicts especially north of Chicago and seems to predict more accurately at the southern end. I would argue that my model does a better job at predicting the actual rodent complaints because captures local variation better in areas that the KDE baseline model did not. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#6.3 Where does the model work well?  \n\n#look where the model does not predict well \n\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countrodent_data_filter - prediction_nb,\n    error_kde = countrodent_data_filter - prediction_kde,\n    abs_error_nb = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\n# Map errors\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_crime()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Create nice summary table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    across(where(is.numeric), ~round(., 3))\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Final Model Summary \n\nmodel_summary %>%\n  kable(\n    caption = \"Final Negative Binomial Model Coefficients (Exponentiated)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = \"Rate ratios > 1 indicate positive association with rodent counts.\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 2.792 </td>\n   <td style=\"text-align:right;\"> 0.088 </td>\n   <td style=\"text-align:right;\"> 31.590 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> carts </td>\n   <td style=\"text-align:right;\"> 0.024 </td>\n   <td style=\"text-align:right;\"> 0.003 </td>\n   <td style=\"text-align:right;\"> 8.683 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> carts.nn </td>\n   <td style=\"text-align:right;\"> -0.004 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -19.868 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 4.338 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> .theta </td>\n   <td style=\"text-align:right;\"> 1.026 </td>\n   <td style=\"text-align:right;\"> 0.040 </td>\n   <td style=\"text-align:right;\"> 25.803 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with rodent counts.</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\nAnalysis: From the mapped errors or residuals, we see that higher residuals are concentrated in the north of the city, meaning that my model had a harder time predicting rodent complaints in that area. Lower value high residuals are also concentrated in the middle portion of the city. The mapped residuals help to explain where there is over or under prediction. This corresponds with the observations from above where much of the over and under prediction occurred in the northern part of the city. This step is an important part of the analysis to visually see how the residuals of the model compare to the actual dependent variable(rodent complaints). The clustering of residuals in north Chicago suggest that there are some spatial relationships specifically in that part of the city that are not accounted for in my current model. \n\n\n\n",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}